### ISSUE TITLE
fastq_trimmer_by_quality missing import six

### ISSUE THREAD

**Issue by afgane** [galaxyproject/tools-devteam#389] opened 2016-09-08 17:43 UTC
When running installed[ fastq_trimmer_by_quality tool](https://github.com/galaxyproject/tools-devteam/tree/master/tools/fastq_trimmer_by_quality) (at latest revision 04a609b0fdf6), it reports 
```
Traceback (most recent call last):
  File "/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/fastq_trimmer_by_quality/04a609b0fdf6/fastq_trimmer_by_quality/fastq_trimmer_by_quality.py", line 3, in <module>
    from galaxy_utils.sequence.fastq import fastqReader, fastqWriter
  File "/opt/galaxy/galaxy-app/lib/galaxy_utils/sequence/fastq.py", line 7, in <module>
    from six import Iterator, string_types
ImportError: No module named six
```

**Comment by martenson** [comment] 2016-09-30 16:17
some findings:

* https://api.anaconda.org/search?name=galaxy_sequence_utils has only version 1.0.1 so conda can never have non-versionless resolution for this since tool requires 1.0.0
* there is no v1.0.1 in the home repo of the package... (https://github.com/galaxyproject/sequence_utils)

**Comment by afgane** [comment] 2016-09-30 16:17
This appears to be caused by the order of dependency resolvers that was setup and because fastq.py v1.0.1 is not available in Conda. As an immediate fix, setting the order of dependency resolvers in `dependency_resolvers_conf.xml` as follows fixed the issue:
```
<dependency_resolvers>
  <conda />
  <tool_shed_packages />
  <galaxy_packages />
  <conda versionless="true" />
  <galaxy_packages versionless="true" />
</dependency_resolvers>
```

**Comment by martenson** [comment] 2016-09-30 16:18
@afgane I would call that a workaround rather than solution. I think we still have a bug in either Galaxy/Conda handling identical imports or in understanding how `versionless` resultion works

**Comment by martenson** [comment] 2016-09-30 16:19
ping @jmchilton @bgruening @mvdbeek

**Comment by jmchilton** [comment] 2016-09-30 16:20
What was broken resolver configuration? Does the default work?

```
<dependency_resolvers>
  <tool_shed_packages />
  <galaxy_packages />
  <galaxy_packages versionless="true" />
  <conda />
  <conda versionless="true" />
</dependency_resolvers>
```

**Comment by afgane** [comment] 2016-09-30 16:21
@jmchilton It was
```
<dependency_resolvers>
  <conda />
  <conda versionless="true" />
  <tool_shed_packages />
  <galaxy_packages />
  <galaxy_packages versionless="true" />
</dependency_resolvers>
```

@martenson Updated the comment to say workaround.

**Comment by jmchilton** [comment] 2016-09-30 16:22
This isn't a bug then right? Conda versionless should never be before:

```
  <tool_shed_packages />
  <galaxy_packages />
```

Your letting any given version resolve with conda - instead of the right version with tool shed or Galaxy packages.

**Comment by martenson** [comment] 2016-09-30 23:19
@jmchilton The `any given version resolve with conda` situation should have worked in this case. I believe, that under the given configuration, it should have auto installed the 1.0.1 version from Conda and work fine. Instead it tried to import from Galaxy - does this mean it even skipped the `<tool_shed_packages />` config entry? - because the TS package has been also installed on the instance. 

As I see it either the package is broken in Conda somehow or our resolution system does not work in this case.

**Comment by jmchilton** [comment] 2016-10-01 00:44
I see I thought the problem was version 1.0.1 was incompatible with 1.0.0. So I guess the problem is that the tool shed version of the install puts its variant of this ahead of Galaxy on the PYTHONPATH - but the conda resolved version puts ``$GALAXY_ROOT/lib`` first? If that is the case hopefully only this package has that problem.

**Comment by martenson** [comment] 2016-10-01 00:55
@jmchilton Sorry for not explaining this better previously. 

I believe there are more tools that could end up importing from Galaxy instead of the proper package. This affects reproducibility because in case there was no import error and code was different the tool would run but reproducing it on a different Galaxy would be a nightmare.

**Comment by jmchilton** [comment] 2016-10-01 00:58
Entering for the record - the way Galaxy modifies the PYTHONPATH - the things in ``lib``  (galaxy, galaxy_utils, galaxy_ext, tool_shed) will mask conda dependencies.

```
(/home/john/workspace/galaxy/database/jobs_directory/000/132/conda-env)  $ python                             
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import galaxy_utils
>>> galaxy_utils
<module 'galaxy_utils' from '/home/john/workspace/galaxy/database/jobs_directory/000/132/conda-env/lib/python2.7/site-packages/galaxy_utils/__init__.pyc'>
>>> 
(/home/john/workspace/galaxy/database/jobs_directory/000/132/conda-env)  $ export PYTHONPATH=/home/john/workspace/galaxy/lib
(/home/john/workspace/galaxy/database/jobs_directory/000/132/conda-env) $ python                                           
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import galaxy_utils
>>> galaxy_utils
<module 'galaxy_utils' from '/home/john/workspace/galaxy/lib/galaxy_utils/__init__.pyc'>
```

**Comment by jmchilton** [comment] 2016-10-01 00:59
@martenson - this shouldn't apply to Galaxy's virtualenv - just ``lib`` - are you sure it is still a nightmare?

**Comment by jmchilton** [comment] 2016-10-01 01:09
I'm tempted to say that if anything is resolved by any of the dependency resolution we should rip Galaxy out of the PYTHONPATH - but the __SET_METADATA__ needs both Conda and Galaxy...

New approach to fix this... @natefoo / @blankenberg what do yinz think about explicitly whitelisting tools that we expose ``lib/`` to. There are some that need it and we need to provide backward compatibility - but we can require them to be registered. The downside is that if people have local tools that touch that stuff (:frowning:) - then they will need to add these to their local whitelist. The upside - no future tools will accidentally require this stuff. We extend the same idea to the Galaxy's virtual environment. I think the whitelist has a good chance of essentially making things backward compatible while make the dependency picture much clearer for tools prospectively.

**Comment by martenson** [comment] 2016-10-01 01:09
@jmchilton iiuc this would affect all tools that depend on `package_galaxy_ops_1_0_0` and `package_galaxy_utils_1_0` (there are at least 30 tools like that just in devteam repo) and anything else that matches the path also. Feels like a bug.

**Comment by jmchilton** [comment] 2016-10-01 01:13
@martenson Point taken - I forgotten about galaxy_ops. Any objections from any corner to just disabling the addition of Galaxy to PYTHONPATH if the tool is a tool shed tool?

**Comment by martenson** [comment] 2016-10-01 01:13
I like the whitelist. Can we auto-whitelist local tools?

**Comment by martenson** [comment] 2016-10-01 01:14
@jmchilton you read my mind :D

**Comment by martenson** [comment] 2016-10-01 01:18
@jmchilton What about that beer? Gonna hit Happy Valley Brewery in an hour or so. Come and join us!

**Comment by jmchilton** [comment] 2016-10-01 01:19
@martenson I'm home alone with a sleeping child in the other room or I definitely would. Enjoy the :beers:!

**Comment by martenson** [comment] 2016-10-01 01:29
I think we can safely close this issue and continue in the one linked above. Thanks all.

**Closed by martenson** 2016-10-01 01:29 UTC
Labels: bug
