### ISSUE TITLE
Error parsing DT tag sam_merge ("Merge Bam Files" in UI)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#158] opened 2015-06-18 02:20 UTC
When using the date tag (DT) in the format specified on the BWA tool form for read group info, this tool produces an error dataset. Clicking on the bug icon contains this error. Similar to error for MergeSAMFiles (issue #157). Related to other issues with this same tool (not recognizing unsorted input even though the checkbox specifying unsorted input is used) - in issue #159)

```Fatal error: Matched on error:
[Mon Jun 15 23:55:53 UTC 2015] net.sf.picard.sam.MergeSamFiles INPUT=[/mnt/galaxy/files/000/dataset_216.dat, /mnt/galaxy/files/000/dataset_217.dat] OUTPUT=/mnt/galaxy/files/000/dataset_218.dat MERGE_SEQUENCE_DICTIONARIES=true TMP_DIR=[/mnt/galaxy/tmp] VALIDATION_STRINGENCY=LENIENT    SORT_ORDER=coordinate ASSUME_SORTED=false USE_THREADING=false VERBOSITY=INFO QUIET=false COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false
[Mon Jun 15 23:55:53 UTC 2015] Executing as galaxy@w3 on Linux 3.13.0-44-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_80-b15
Ignoring SAM validation error: WARNING: File /mnt/galaxy/files/000/dataset_216.dat, Error parsing SAM header. DT tag value '$rg.DT' is not parseable as a date. Line:
@RG	ID:one	SM:one	PL:ILLUMINA	LB:$rg.LB	CN:$rg.CN	DS:$rg.DS	DT:$rg.DT	PU:$rg.PU
Ignoring SAM validation error: ERROR: File /mnt/galaxy/files/000/dataset_216.dat, Error parsing SAM header. Problem parsing @PG key:value pair ID:one clashes with ID:bwa. Line:
@PG	ID:bwa	PN:bwa	VN:0.7.10-r876-dirty	CL:bwa sampe -r @RG	ID:one	SM:one	PL:ILLUMINA	LB:$rg.LB	CN:$rg.CN	DS:$rg.DS	DT:$rg.DT	PU:$rg.PU /mnt/galaxyIndices/hg19/bwa_mem_index/hg19/hg19.fa first.sai second.sai /mnt/galaxy/files/000/dataset_113.dat /mnt/galaxy/files/000/dataset_114.dat
Ignoring SAM validation error: WARNING: File /mnt/galaxy/files/000/dataset_217.dat, Error parsing SAM header. DT tag value '$rg.DT' is not parseable as a date. Line:
@RG	ID:two	SM:two	PL:ILLUMINA	LB:$rg.LB	CN:$rg.CN	DS:$rg.DS	DT:$rg.DT	PU:$rg.PU
Ignoring SAM validation error: ERROR: File /mnt/galaxy/files/000/dataset_217.dat, Error parsing SAM header. Problem parsing @PG key:value pair ID:two clashes with ID:bwa. Line:
@PG	ID:bwa	PN:bwa	VN:0.7.10-r876-dirty	CL:bwa sampe -r @RG	ID:two	SM:two	PL:ILLUMINA	LB:$rg.LB	CN:$rg.CN	DS:$rg.DS	DT:$rg.DT	PU:$rg.PU /mnt/galaxyIndices/hg19/bwa_mem_index/hg19/hg19.fa first.sai second.sai /mnt/galaxy/files/000/dataset_115.dat /mnt/galaxy/files/000/dataset_116.dat
INFO	2015-06-15 23:55:53	MergeSamFiles	Input files are in same order as output so sorting to temp directory is not needed.
INFO	2015-06-15 23:55:57	MergeSamFiles	Finished reading inputs.
[Mon Jun 15 23:55:57 UTC 2015] net.sf.picard.sam.MergeSamFiles done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=236453888```

Galaxy Tool Version 1.2.0

**Comment by nsoranzo** [comment] 2015-06-18 10:52
Duplicate of #157.

**Closed by nsoranzo** 2015-06-18 10:52 UTC
