### ISSUE TITLE
`samtools_sort` cannot properly sort by name

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/tools-devteam#210] opened 2015-08-19 20:42 UTC
When sorting by read name using `samtools_sort` Galaxy is unable to generate a BAM index and thus the dataset ends up in an "error" state. This makes it impoosible to use a tool like bedtools bamtobed using the -bedpe option (since it requires name sorted bam files).

```
Traceback (most recent call last):
  File "/data/local/galaxy/galaxy-prod/lib/galaxy/jobs/runners/local.py", line 129, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/data/local/galaxy/galaxy-prod/lib/galaxy/jobs/__init__.py", line 1199, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/data/local/galaxy/galaxy-prod/lib/galaxy/datatypes/binary.py", line 301, in set_meta
    raise Exception, "Error Setting BAM Metadata: %s" % stderr
Exception: Error Setting BAM Metadata: [bam_index_core] the alignment is not sorted: reads without coordinates prior to reads with coordinates.
```

A possible solution would be to implement an new bam datatype (sorted by name, and possibly one unsorted?).

**Comment by bgruening** [comment] 2015-08-19 21:26
@lparsons this is a Galaxy bug with the new pysam based BAM metadata: https://github.com/galaxyproject/galaxy/pull/476

**Comment by jennaj** [comment] 2015-10-06 21:09
This Trello ticket is a duplicate of this issue. Will point it here. https://trello.com/c/lwAdo5NG

**Comment by bgruening** [comment] 2015-10-07 06:26
This one here as well https://twitter.com/KeywanHP/status/651157003306319873

**Comment by bgruening** [comment] 2015-10-07 06:27
I at least fixed the bedtools bug and we don't need to sort before. Very poor attempt to fix this one by one but what should be do.
@lparsons I will close this one. Please feel free to reopen if you encounter additional errors.

**Closed** 2015-10-10 08:16 UTC
