### ISSUE TITLE
Error parsing DT tag with picard_sortsam

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-devteam#161] opened 2015-06-18 02:37 UTC
Related to #157 and #158. Most likely exists in other tools from this revision/package.

Green "success" dataset with this in the info field:

```Picked up _JAVA_OPTIONS: -Xmx2048m -Xms256m
Ignoring SAM validation error: WARNING: Error parsing SAM header. DT tag value '$rg.DT' is not parseable as a date. Line:
@RG	ID:one	PL:ILLUMINA	PU:$rg.PU	LB:$rg.LB	DS:$rg.DS	DT:$rg.DT	SM:one	CN:$rg.CN
Ignoring```

**Comment by bgruening** [comment] 2015-06-18 08:56
This looks like the same error in https://github.com/galaxyproject/tools-devteam/issues/157 and is actually a BWA wrapper problem as far as I can tell.

**Comment by nsoranzo** [comment] 2015-06-18 11:24
Duplicate of #157.

**Closed by nsoranzo** 2015-06-18 11:24 UTC
